"""Add orders table

Revision ID: 6bc6e78da04f
Revises: 207c41e0acba
Create Date: 2025-08-05 23:12:49.498331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc6e78da04f'
down_revision: Union[str, None] = '1a8c414468e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='payment_status_enum')
    payment_method_enum = sa.Enum('CASH', 'CARD', 'PAYME', 'CLICK', name='payment_method_enum')

    payment_status_enum.create(op.get_bind(), checkfirst=True)
    payment_method_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('orders', sa.Column('cart_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_latitude', sa.Numeric(precision=10, scale=8), nullable=False))
    op.add_column('orders', sa.Column('delivery_longitude', sa.Numeric(precision=11, scale=8), nullable=False))
    op.add_column('orders', sa.Column('house_number', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('entrance_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('level', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('apartment_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_notes', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', payment_status_enum, nullable=False))
    op.add_column('orders', sa.Column('payment_method', payment_method_enum, nullable=False))
    op.add_column('orders', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'scheduled_time')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'delivery_notes')
    op.drop_column('orders', 'apartment_number')
    op.drop_column('orders', 'level')
    op.drop_column('orders', 'entrance_number')
    op.drop_column('orders', 'house_number')
    op.drop_column('orders', 'delivery_longitude')
    op.drop_column('orders', 'delivery_latitude')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'cart_id')
    # ### end Alembic commands ###
