"""Make meal name field unique in meals table

Revision ID: e83fe620a00e
Revises: 93a9af2d464b
Create Date: 2025-07-17 15:10:26.914649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83fe620a00e'
down_revision: Union[str, None] = '93a9af2d464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meals', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals', type_='unique')
    # ### end Alembic commands ###
