"""Remove unique constraint on meal_name field in cart_items table

Revision ID: 76d4a146dfcd
Revises: e0accec0943c
Create Date: 2025-07-24 17:07:22.514572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d4a146dfcd'
down_revision: Union[str, None] = 'e0accec0943c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_meal_name_key', 'cart_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_items_meal_name_key', 'cart_items', ['meal_name'])
    # ### end Alembic commands ###
