"""Make combination of provider and username fields as unique in user_identities

Revision ID: 9e1e89a2cbf4
Revises: baca489c2c8f
Create Date: 2025-07-23 12:51:15.262099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1e89a2cbf4'
down_revision: Union[str, None] = 'baca489c2c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_provider_username', 'user_identities', ['provider', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_username', 'user_identities', type_='unique')
    # ### end Alembic commands ###
