"""Add meal_name field to cart_items table

Revision ID: e0accec0943c
Revises: 9e1e89a2cbf4
Create Date: 2025-07-24 16:53:53.151931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0accec0943c'
down_revision: Union[str, None] = '9e1e89a2cbf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('meal_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'cart_items', ['meal_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='unique')
    op.drop_column('cart_items', 'meal_name')
    # ### end Alembic commands ###
