"""Add carts and cart_items tables

Revision ID: e32031e93d52
Revises: 1bfee8fb2388
Create Date: 2025-07-19 00:48:46.766537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32031e93d52'
down_revision: Union[str, None] = '1bfee8fb2388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=False))
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('cart_items_user_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_user_id_fkey', 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'created_at')
    op.drop_column('cart_items', 'cart_id')
    op.drop_table('carts')
    # ### end Alembic commands ###
