"""Rename price field into unit_price in meals table

Revision ID: fd468fc42b66
Revises: e32031e93d52
Create Date: 2025-07-20 11:06:25.418953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd468fc42b66'
down_revision: Union[str, None] = 'e32031e93d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('meals', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('meals', 'unit_price')
    # ### end Alembic commands ###
