"""Add tables orders and order_items, add total_price fields in cart and cart_items

Revision ID: ff6faeff2f2a
Revises: 76d4a146dfcd
Create Date: 2025-07-27 18:01:27.855668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6faeff2f2a'
down_revision: Union[str, None] = '76d4a146dfcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('cart_items', 'unit_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('carts', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'total_price')
    op.alter_column('cart_items', 'unit_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('cart_items', 'total_price')
    # ### end Alembic commands ###
